"""eBay output template schema, extracted verbatim from the example Output.xlsx."""

OUTPUT_HEADERS = [
    "*Action(SiteID=UK|Country=GB|Currency=GBP|Version=1193)",
    "Custom label (SKU)",
    "Title",
    "Description",
    "PicURL",
    "Category",
    "Start price",
    "OriginalRetailPrice",
    "SoldOneBay",
    "Quantity",
    "Condition ID",
    "ConditionDescription",
    "Format",
    "Duration",
    "Currency",
    "VAT%",
    "Location",
    "Shipping profile name",
    "Return profile name",
    "Payment profile name",
    "Schedule Time",
    "Best Offer Enabled",
    "StoreCategory",
    "C:Pit to Pit (inches)",
    "C:Length (inches)",
    "C:Arm (inches)",
    "C:Waist Laying Flat (inches)",
    "C:Inside Leg (inches)",
    "C:Barcode",
    "C:Brand",
    "C:Colour",
    "C:Department",
    "C:Size",
    "C:Style",
    "C:Character",
    "C:Fabric Type",
    "C:Fabric Wash",
    "C:Features",
    "C:Fit",
    "C:Front Type",
    "C:Inside Leg",
    "C:Material",
    "C:Occasion",
    "C:Size Type",
    "C:Theme",
    "C:Vintage",
    "C:Waist Size",
    "C:Accents",
    "C:Closure",
    "C:Country of Origin",
    "C:Fabric Weight",
    "C:Garment Care",
    "C:Handmade",
    "C:MPN",
    "C:Pattern",
    "C:Personalisation Instructions",
    "C:Personalise",
    "C:Pocket Type",
    "C:Rise",
    "C:Season",
    "C:Unit Quantity",
    "C:Unit Type",
    "C:Neckline",
    "C:Sleeve Length",
    "C:Type",
    "C:Chest Size",
    "C:Collar Style",
    "C:Model",
    "C:Product Line",
    "C:Outer Shell Material",
    "C:Insulation Material",
    "C:Lining Material",
    "C:Performance/Activity",
    "C:Jacket/Coat Length",
    "C:Warmth Weight",
    "C:Leg Style",
    "C:Jacket Cut",
    "C:Jacket Lapel Style",
    "C:Number of Pieces",
    "C:Jacket Front Button Style",
    "C:Jacket Sleeve Button Style",
    "C:Jacket Vent Style",
    "C:Item Length",
    "C:Item Width",
    "C:Year Manufactured",
    "C:Charm Type",
    "C:Cut Grade",
    "C:Hallmarked",
    "C:Main Stone",
    "C:Main Stone Colour",
    "C:Main Stone Creation",
    "C:Main Stone Shape",
    "C:Main Stone Treatment",
    "C:Materials sourced from",
    "C:Metal",
    "C:Metal Purity",
    "C:Number of Gemstones",
    "C:Secondary Stone",
    "C:Setting Style",
    "C:Shape",
    "C:Antique",
    "C:Base Metal",
    "C:Chain Type",
    "C:Customised",
    "C:Era",
    "C:Gemstone Clarity Grade",
    "C:Main Stone Depth",
    "C:Main Stone Length",
    "C:Main Stone Width",
    "C:Seller Warranty",
    "C:Signed",
    "C:Sizable",
    "C:Wholesale",
    "C:Ear Area",
    "C:Item Diameter",
    "C:Knit Style",
    "C:Character Family",
    "C:Jumper Length",
    "C:Certification",
    "C:Coloured Diamond Intensity",
    "C:Diamond Clarity Grade",
    "C:Diamond Colour Grade",
    "C:Necklace Length",
    "C:Total Carat Weight",
    "C:Collection",
    "C:Number of Diamonds",
    "C:Pendant Shape",
    "C:Pendant/Locket Type",
    "C:Shirt Length",
    "C:Ring Size",
    "C:Band Width",
]

# Fields we populate deterministically from source data (never from the AI).
DETERMINISTIC_FIELDS = {
    "*Action(SiteID=UK|Country=GB|Currency=GBP|Version=1193)",
    "Custom label (SKU)",
    "PicURL",
    "Category",
    "Start price",
    "OriginalRetailPrice",
    "SoldOneBay",
    "Quantity",
    "Format",
    "Duration",
    "Currency",
    "VAT%",
    "Location",
    "Shipping profile name",
    "Return profile name",
    "Payment profile name",
    "Schedule Time",
    "Best Offer Enabled",
    "StoreCategory",
    "C:Pit to Pit (inches)",
    "C:Length (inches)",
    "C:Arm (inches)",
    "C:Waist Laying Flat (inches)",
    "C:Inside Leg (inches)",
    "C:Barcode",
    "C:Brand",
    "C:Colour",
    "C:Department",
    "C:Size",
    "C:Country of Origin",
}

# Everything else (Title, Description, Condition ID, ConditionDescription, and
# every remaining "C:" item-specific field) is filled in by the AI content
# generator, one JSON object per product.
AI_FIELDS = [h for h in OUTPUT_HEADERS if h not in DETERMINISTIC_FIELDS]
